server:
  port: 8888
spring:
  main:
    banner-mode: off
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:~/testdb;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2-console
mybatis:
  mapper-locations: classpath:sqlmap/**/*.xml
  config-location: classpath:mybatis-config.xml